Asp.Net end project/Models/Banner.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Models
{
    public class Banner : BaseEntity
    {
        public string Image { get; set; }
        public string SubTitle { get; set; }
        public string Title { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Can't be empty")]
        public IFormFile Photo { get; set; }
    }
}

Asp.Net end project/Areas/AdminArea/Controllers/BannerController.cs
using Asp.Net_end_project.Data;
using Asp.Net_end_project.Helpers;
using Asp.Net_end_project.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class BannerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public BannerController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Banner> banners = await _context.Banners.Where(m => !m.IsDeleted).ToListAsync();
            return View(banners);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Banner banner)
        {
            if (!ModelState.IsValid) return View();

            if (!banner.Photo.CheckFileType("image/"))
            {
                ModelState.AddModelError("Photo", "Please choose correct image type");
                return View();
            }

            if (!banner.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", "Please choose correct image size");
                return View();
            }

            string fileName = Guid.NewGuid().ToString() + "_" + banner.Photo.FileName;

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", fileName);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await banner.Photo.CopyToAsync(stream);
            }

            banner.Image = fileName;

            await _context.Banners.AddAsync(banner);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            Banner banner = await _context.Banners.FindAsync(id);

            if (banner == null) return NotFound();

            return View(banner);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                Banner banner = await _context.Banners.FirstOrDefaultAsync(m => m.Id == id);

                if (banner is null) return NotFound();

                return View(banner);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Banner banner)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(banner);
                }

                if (!banner.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Please choose correct image type");
                    return View();
                }

                string fileName = Guid.NewGuid().ToString() + "_" + banner.Photo.FileName;

                Banner dbBanner = await _context.Banners.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbBanner is null) return NotFound();

                if (dbBanner.Photo == banner.Photo)
                {
                    return RedirectToAction(nameof(Index));
                }

                string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", fileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await banner.Photo.CopyToAsync(stream);
                }

                banner.Image = fileName;

                _context.Banners.Update(banner);

                await _context.SaveChangesAsync();

                string dbPath = Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", dbBanner.Image);

                Helper.DeleteFile(dbPath);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            Banner banner = await GetByIdAsync(id);

            if (banner == null) return NotFound();

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/banner", banner.Image);

            Helper.DeleteFile(path);


            _context.Banners.Remove(banner);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private async Task<Banner> GetByIdAsync(int id)
        {
            return await _context.Banners.FindAsync(id);
        }
    }
}

Asp.Net end project/Areas/AdminArea/Views/Banner/Create.cshtml
@model Banner
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:blue; text-align:center">- Create Banner -</h3>

                    <form asp-controller="Banner" asp-action="Create" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                            <div>
                                <label for="exampleInputUsername1">SubTitle</label>
                                <textarea class="form-control rounded-0" asp-for="SubTitle" id="SubTitle-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="SubTitle"></span>
                            </div>
                            <div>
                                <label for="exampleInputUsername1">Title</label>

                                <textarea class="form-control rounded-0" asp-for="Title" id="Title-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Create</button>
                        <a asp-controller="Banner" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />

    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("SubTitle-area")
        CKEDITOR.replace("Title-area")
    </script>
}

Asp.Net end project/Areas/AdminArea/Views/Banner/Detail.cshtml
@model Banner
@{
    ViewData["Title"] = "Detail";
}

<div class="container">
    <div class="table-responsive pt-3">
        <table class="table table-bordered">
            <thead>
                <tr>

                    <th>
                        Image
                    </th>
                    <th>
                        SubTitle
                    </th>
                    <th>
                        Title
                    </th>
                </tr>

            </thead>
            <tbody>
                <tr class="table-info">
                    <td>
                        <img style="width:100px; height:100px;border-radius:0 !important " src="~/assets/img/banner/@Model.Image" alt="slider" />
                    </td>
                    <td>
                        @Model.SubTitle
                    </td>
                    <td>
                        @Model.Title
                    </td>
                </tr>

            </tbody>
        </table>
    </div>
    <a asp-controller="Service" asp-action="Index" class="btn btn-primary my-3">Back</a>
</div>

Asp.Net end project/Areas/AdminArea/Views/Banner/Edit.cshtml
@model Banner
@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    <div class="row my-5">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:blue; text-align:center">- Edit Banner -</h3>

                    <form asp-controller="Banner" asp-action="Edit" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                            <div>
                                <label for="exampleInputUsername1">SubTitle</label>
                                <textarea class="form-control rounded-0" asp-for="SubTitle" id="SubTitle-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="SubTitle"></span>
                            </div>
                            <div>
                                <label for="exampleInputUsername1">Title</label>

                                <textarea class="form-control rounded-0" asp-for="Title" id="Title-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Edit</button>
                        <a asp-controller="Banner" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />

    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("SubTitle-area")
        CKEDITOR.replace("Title-area")
    </script>
}

Asp.Net end project/Areas/AdminArea/Views/Banner/Index.cshtml
@model IEnumerable<Banner>
@{
    ViewData["Title"] = "Banner";
}

<div class="container-fluid my-3 mx-3">
    <div class="col-lg-12 stretch-card">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title" style="text-align:center;color:blue">- Index -</h2>
                <div class="create-btn mb-3">
                    <a asp-area="AdminArea" asp-controller="Banner" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    SubTitle
                                </th>
                                <th>
                                    Title
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var banner in Model)
                            {
                                <tr class="table-info">

                                    <td>
                                        <img style="width:100px; height:100px;border-radius:0 !important " src="~/assets/img/banner/@banner.Image" alt="slider" />
                                    </td>
                                    <td>
                                        @Html.Raw(banner.SubTitle)
                                    </td>
                                    <td style="width:350px">
                                        @Html.Raw(banner.Title)
                                    </td>
                                    <td id="parent-image" style="text-align: center;">
                                        <a asp-action="Detail" asp-route-id="@banner.Id" class="btn btn-info"><i class="mdi mdi-information mx-0 text-white"></i></a>
                                        <a asp-action="Edit" asp-route-id="@banner.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></a>
                                        <form id="parent-image" style="display: inline-block;" asp-action="Delete" asp-route-id="@banner.Id" method="post">
                                            <button data-id="@banner.Id" type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>