Asp.Net end project/Models/Brand.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Models
{
    public class Brand : BaseEntity
    {
        public string Image { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Can't be empty")]
        public IFormFile Photo { get; set; }
    }
}

Asp.Net end project/Areas/AdminArea/Controllers/BrandController.cs
using Asp.Net_end_project.Data;
using Asp.Net_end_project.Helpers;
using Asp.Net_end_project.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class BrandController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public BrandController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Brand> brands = await _context.Brands.Where(m => !m.IsDeleted).AsNoTracking().ToListAsync();
            return View(brands);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Brand brand)
        {
            if (!ModelState.IsValid) return View();

            if (!brand.Photo.CheckFileType("image/"))
            {
                ModelState.AddModelError("Photo", "Please choose correct image type");
                return View();
            }

            if (!brand.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", "Please choose correct image size");
                return View();
            }

            string fileName = Guid.NewGuid().ToString() + "_" + brand.Photo.FileName;

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/brand", fileName);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await brand.Photo.CopyToAsync(stream);
            }

            brand.Image = fileName;
            await _context.Brands.AddAsync(brand);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            Brand brand = await _context.Brands.FindAsync(id);

            if (brand == null) return NotFound();

            return View(brand);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                Brand brand = await _context.Brands.FirstOrDefaultAsync(m => m.Id == id);

                if (brand is null) return NotFound();

                return View(brand);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Brand brand)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(brand);
                }

                if (!brand.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Please choose correct image type");
                    return View();
                }

                string fileName = Guid.NewGuid().ToString() + "_" + brand.Photo.FileName;

                Brand dbBrand = await _context.Brands.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbBrand is null) return NotFound();

                if (dbBrand.Photo == brand.Photo)
                {
                    return RedirectToAction(nameof(Index));
                }

                string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/brand", fileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await brand.Photo.CopyToAsync(stream);
                }

                brand.Image = fileName;

                _context.Brands.Update(brand);

                await _context.SaveChangesAsync();

                string dbPath = Helper.GetFilePath(_env.WebRootPath, "assets/img/brand", dbBrand.Image);

                Helper.DeleteFile(dbPath);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }


        public async Task<IActionResult> Delete(int id)
        {

            Brand brand = await GetByIdAsync(id);

            if (brand == null) return NotFound();

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/brand", brand.Image);

            Helper.DeleteFile(path);

            _context.Brands.Remove(brand);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private async Task<Brand> GetByIdAsync(int id)
        {
            return await _context.Brands.FindAsync(id);
        }
    }
}

Asp.Net end project/Areas/AdminArea/Views/Brand/Create.cshtml
@model Brand
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row my-5">

        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:blue; text-align:center">- Create Brand -</h3>

                    <form asp-controller="Brand" asp-action="Create" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">

                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary me-2">Create</button>
                        <a asp-controller="Brand" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />
}

Asp.Net end project/Areas/AdminArea/Views/Brand/Detail.cshtml
@model Brand
@{
    ViewData["Title"] = "Detail";
}

<div class="container">
    <div class="table-responsive pt-3">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Image
                    </th>
                </tr>

            </thead>
            <tbody>
                <tr class="table-info">
                    <td>
                        <img style="width:250px; height:150px;border-radius:0 !important " src="~/assets/img/brand/@Model.Image" alt="slider" />
                    </td>
                </tr>

            </tbody>
        </table>
    </div>
    <a asp-controller="Brand" asp-action="Index" class="btn btn-primary my-3">Back</a>
</div>

Asp.Net end project/Areas/AdminArea/Views/Brand/Edit.cshtml
@model Brand
@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    <div class="row my-5">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:blue; text-align:center">- Edit Brand -</h3>
                    <form asp-controller="Brand" asp-action="Edit" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary me-2">Edit</button>
                        <a asp-controller="Brand" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@*@section Scripts{
    <partial name="_ValidationPartial" />
}*@

Asp.Net end project/Areas/AdminArea/Views/Brand/Index.cshtml
@model IEnumerable<Brand>
@{
    ViewData["Title"] = "Brand";
}

<div class="container-fluid my-3 mx-3">
    <div class="col-lg-12 stretch-card">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title" style="text-align:center;color:blue">- Index -</h2>
                <div class="create-btn mb-3">
                    <a asp-area="AdminArea" asp-controller="Brand" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var brand in Model)
                            {
                                <tr class="table-info">
                                    <td>
                                        <img style="width:200px; height:100px;border-radius:0 !important " src="~/assets/img/brand/@brand.Image" alt="slider" />
                                    </td>
                                    <td id="parent-image" style="text-align: center;">
                                        <a asp-action="Detail" asp-route-id="@brand.Id" class="btn btn-info"><i class="mdi mdi-information mx-0 text-white"></i></a>
                                        <a asp-action="Edit" asp-route-id="@brand.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></a>
                                        <form id="parent-image" style="display: inline-block;" asp-action="Delete" asp-route-id="@brand.Id" method="post">
                                            <button data-id="@brand.Id" type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i></button>
                                        </form>
                                    </td>
                                </tr>
                             }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>