Asp.Net end project/Models/Slider.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Models
{
    public class Slider : BaseEntity
    {
        public string Image { get; set; }
        public string Sale { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Can't be empty")]
        public IFormFile Photo { get; set; }
    }
}

Asp.Net end project/Areas/AdminArea/Controllers/SliderController.cs
using Asp.Net_end_project.Data;
using Asp.Net_end_project.Helpers;
using Asp.Net_end_project.Models;
using Asp.Net_end_project.ViewModels.SliderViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public SliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Slider> sliders = await _context.Sliders.Where(m => !m.IsDeleted).AsNoTracking().ToListAsync();
            return View(sliders);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Slider slider)
        {
            if (!ModelState.IsValid) return View();

            if (!slider.Photo.CheckFileType("image/"))
            {
                ModelState.AddModelError("Photo", "Please choose correct image type");
                return View();
            }

            if (!slider.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", "Please choose correct image size");
                return View();
            }

            string fileName = Guid.NewGuid().ToString() + "_" + slider.Photo.FileName;

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", fileName);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await slider.Photo.CopyToAsync(stream);
            }

            slider.Image = fileName;

            await _context.Sliders.AddAsync(slider);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            Slider slider = await _context.Sliders.FindAsync(id);

            if (slider == null) return NotFound();

            return View(slider);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                Slider slider = await _context.Sliders.FirstOrDefaultAsync(m => m.Id == id);

                if (slider is null) return NotFound();

                return View(slider);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Slider slider)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(slider);
                }

                if (!slider.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Please choose correct image type");
                    return View();
                }

                string fileName = Guid.NewGuid().ToString() + "_" + slider.Photo.FileName;

                Slider dbSlider = await _context.Sliders.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbSlider is null) return NotFound();

                if (dbSlider.Photo == slider.Photo)
                {
                    return RedirectToAction(nameof(Index));
                }

                string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", fileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await slider.Photo.CopyToAsync(stream);
                }

                slider.Image = fileName;

                _context.Sliders.Update(slider);

                await _context.SaveChangesAsync();

                string dbPath = Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", dbSlider.Image);

                Helper.DeleteFile(dbPath);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
          
            Slider slider = await GetByIdAsync(id);

            if (slider == null) return NotFound();

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img/slider", slider.Image);

            Helper.DeleteFile(path);

            _context.Sliders.Remove(slider);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private async Task<Slider> GetByIdAsync(int id)
        {
            return await _context.Sliders.FindAsync(id);
        }
    }
}

Asp.Net end project/Areas/AdminArea/Views/Slider/Create.cshtml
@model Slider
@{
    ViewData["Title"] = "Create";
}
<div class="container">
    <div class="row my-5">
        
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:blue; text-align:center">- Create Slider -</h3>

                    <form asp-controller="Slider" asp-action="Create" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">

                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>


                            <div>
                                <label for="exampleInputUsername1">Sale</label>
                                <textarea class="form-control rounded-0" asp-for="Sale" id="Sale-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Sale"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Title</label>
                                <textarea class="form-control rounded-0" asp-for="Title" id="Title-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Description</label>
                                <textarea class="form-control rounded-0" asp-for="Description" id="Description-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>



                        </div>

                        <button type="submit" class="btn btn-primary me-2">Create</button>
                        <a asp-controller="Slider" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />

    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("Sale-area")
        CKEDITOR.replace("Title-area")
        CKEDITOR.replace("Description-area")
    </script>
}

Asp.Net end project/Areas/AdminArea/Views/Slider/Detail.cshtml
@model Slider
@{
    ViewData["Title"] = "Detail";
}
<div class="container">
    <div class="table-responsive pt-3">
        <table class="table table-bordered">
            <thead>
                <tr>

                    <th>
                        Image
                    </th>
                    <th>
                        Sale
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Description
                    </th>
                 
                </tr>

            </thead>
            <tbody>
                <tr class="table-info">
                    <td>
                        <img style="width:100px; height:100px;border-radius:0 !important " src="~/assets/img/slider/@Model.Image" alt="slider" />
                    </td>
                    <td>
                        @Model.Sale
                    </td>
                    <td>
                        @Model.Title
                    </td>
                    <td style="width:350px">
                        @Model.Description
                    </td>

                </tr>

            </tbody>
        </table>
    </div>

    <a asp-controller="Slider" asp-action="Index" class="btn btn-primary my-3">Back</a>
</div>

Asp.Net end project/Areas/AdminArea/Views/Slider/Edit.cshtml
@model Slider
@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row my-5">

        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 style="color:blue; text-align:center">- Edit Slider -</h3>

                    <form asp-controller="Slider" asp-action="Edit" class="forms-sample" method="post" enctype="multipart/form-data">
                        <div class="form-group">

                            <div>
                                <label for="exampleInputUsername1">Image</label>
                                <input class="form-control" asp-for="Photo">
                                <span class="text-danger" asp-validation-for="Photo"></span>
                            </div>


                            <div>
                                <label for="exampleInputUsername1">Sale</label>

                                <textarea class="form-control rounded-0" asp-for="Sale" id="Sale-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Sale"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Header</label>

                                <textarea class="form-control rounded-0" asp-for="Title" id="Title-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Title"></span>
                            </div>

                            <div>
                                <label for="exampleInputUsername1">Description</label>
                                <textarea class="form-control rounded-0" asp-for="Description" id="Description-area" rows="10"></textarea>
                                <span class="text-danger" asp-validation-for="Description"></span>
                            </div>



                        </div>

                        <button type="submit" class="btn btn-primary me-2">Edit</button>
                        <a asp-controller="Slider" asp-action="Index" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />

    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        CKEDITOR.replace("Sale-area")
        CKEDITOR.replace("Title-area")
        CKEDITOR.replace("Description-area")
    </script>
}

Asp.Net end project/Areas/AdminArea/Views/Slider/Index.cshtml
@model IEnumerable<Slider>

@{
    ViewData["Title"] = "Slider";
 }

<div class="container-fluid my-3 mx-3">
    <div class="col-lg-12 stretch-card">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title" style="text-align:center;color:blue">- Index -</h2>
                <div class="create-btn mb-3">
                    <a asp-area="AdminArea" asp-controller="Slider" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
                </div>
                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>

                                <th>
                                    Image
                                </th>
                                <th>
                                    Sale
                                </th>
                                <th>
                                    Title
                                </th>
                                <th>
                                    Description
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var slider in Model)
                            {
                <tr class="table-info">


                    <td>
                        <img style="width:100px; height:100px;border-radius:0 !important " src="~/assets/img/slider/@slider.Image" alt="slider" />
                    </td>
                    <td>
                     @Html.Raw(slider.Sale)
                    </td>
                    <td>
                        @Html.Raw(slider.Title)
                    </td>
                    <td style="width:350px">
                        @Html.Raw(slider.Description)
                    </td>
                    <td id="parent-image" style="text-align: center;">
                        <a asp-action="Detail" asp-route-id="@slider.Id" class="btn btn-info"><i class="mdi mdi-information mx-0 text-white"></i></a>
                        <a asp-action="Edit" asp-route-id="@slider.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></a>
                        <form id="parent-image" style="display: inline-block;" asp-action="Delete" asp-route-id="@slider.Id" method="post">
                            <button data-id="@slider.Id" type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i></button>
                        </form>
                    </td>
                </tr>
}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>