Asp.Net end project/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Models
{
    public class Contact : BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Address { get; set; } 
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }
        public string WorkingHours { get; set; }
    }
}

Asp.Net end project/Areas/AdminArea/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Areas.AdminArea.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Asp.Net end project/Controllers/ContactController.cs
using Asp.Net_end_project.Data;
using Asp.Net_end_project.Models;
using Asp.Net_end_project.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.Net_end_project.Controllers
{
    public class ContactController : Controller
    {
        private readonly AppDbContext _context;
        public ContactController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            Contact contact = await _context.Contacts.Where(m => !m.IsDeleted).FirstOrDefaultAsync();
            SendMessage sendMessage = await _context.SendMessages.Where(m => !m.IsDeleted).FirstOrDefaultAsync();

            ContactVM contactVM = new ContactVM
            {
                Contact = contact,
                SendMessage = new SendMessage()

            };

            return View(contactVM);
        }

      

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(SendMessage sendMessage)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction(nameof(Index));
                }

                bool isExsist = await _context.SendMessages.AnyAsync(m => m.Name.Trim() == sendMessage.Name.Trim() &&
                     m.Email.Trim() == sendMessage.Email.Trim() &&
                     m.Message.Trim() == sendMessage.Message.Trim() &&
                     m.Phone.Trim() == sendMessage.Phone.Trim() &&
                     m.Subject.Trim() == sendMessage.Subject.Trim());

                if (isExsist)
                {
                    ModelState.AddModelError("Name", "Subject is already exist");
                }
                await _context.SendMessages.AddAsync(sendMessage);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {

                return View();
            }
        }
    }
}

Asp.Net end project/Views/Contact/Index.cshtml
@model ContactVM
@{
    ViewData["Title"] = "Contact Page";
}

<!-- main wrapper start -->
<main>
    <!-- breadcrumb area start -->
    <div class="breadcrumb-area bg-img" data-bg="~/assets/img/banner/breadcrumb-banner.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb-wrap text-center">
                        <nav aria-label="breadcrumb">
                            <h1 class="breadcrumb-title">Contact Us</h1>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb area end -->
    <!-- contact wrapper area start -->
    <div class="contact-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="contact-message">
                        <h2 class="contact-title">tell us your project</h2>
                        <form id="contact-form" asp-controller="Contact" asp-action="Index" method="post" class="contact-form">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <input  placeholder="Name *" type="text" asp-for="SendMessage.Name">
                                    <span class="text-danger" asp-validation-for="SendMessage.Name" ></span>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <input placeholder="Phone *" type="text" asp-for="SendMessage.Phone">
                                    <span class="text-danger" asp-validation-for="SendMessage.Phone"></span>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <input placeholder="Email *" type="text" asp-for="SendMessage.Email">
                                    <span class="text-danger" asp-validation-for="SendMessage.Email"></span>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <input  placeholder="Subject *" type="text" asp-for="SendMessage.Subject">
                                    <span class="text-danger" asp-validation-for="SendMessage.Subject"></span>
                                </div>
                                <div class="col-12">
                                    <div class="contact2-textarea text-center">
                                        <input asp-for="SendMessage.Message" placeholder="Message *" type="text" class="form-control2">
                                        <span class="text-danger" asp-validation-for="SendMessage.Message"></span>
                                    </div>
                                    <div class="contact-btn">
                                        <button class="btn" type="submit">Send Message</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="contact-info pt-0">
                        <h2 class="contact-title">@Model.Contact.Title</h2>
                        <p>
                          @Model.Contact.Description
                        </p>
                        <ul>
                            <li><i class="fa fa-fax"></i>@Model.Contact.Address</li>
                            <li><i class="fa fa-phone"></i>@Model.Contact.Email</li>
                            <li><i class="fa fa-envelope-o"></i>@Model.Contact.Phone</li>
                        </ul>
                        <div class="working-time">
                            <h3>Working Hours</h3>
                            <p class="pb-0">
                                @Html.Raw(Model.Contact.WorkingHours)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- contact wrapper area end -->
</main>
<!-- main wrapper end -->